FileBasedDBApplication/Models/JsonStorageTable.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FileBasedDBApplication.Models
{
    public class JsonStorageTable
    {
        [Required]
        [MaxLength(length:32,ErrorMessage ="Key should not more be than 32 chars")]
        public string Key { get; set; }
        [Required]
        [DataType(DataType.MultilineText)]
        [MaxLength(length: 2048, ErrorMessage = "Value should not more be than 2048 chars")]
        public string Value { get; set; }
        
        public int TimeToLive { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool Active { get; set; }
    }
}

FileBasedDBApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FileBasedDBApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            DatabaseAccess db = new DatabaseAccess();
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

FileBasedDBApplication/Controllers/JSonDataObjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FileBasedDBApplication.Models;

namespace FileBasedDBApplication.Controllers
{
    public class JSonDataObjectController : Controller
    {
        DatabaseAccess db = new DatabaseAccess();
        public ActionResult Index()
        {
            return View(db.GetAllJSonDatas());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(JsonStorageTable model)
        {
            if (ModelState.IsValid)
            {
                db.InserJsonData(model);
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Details(string id)
        {
            return View(db.GetAJSonData(id));
        }
        [HttpPost]
        public ActionResult Details(JsonStorageTable model)
        {
           
                JsonStorageTable dbModel = db.GetAJSonData(model.Key);

                if (db.DeleteKey(dbModel))
                 return  RedirectToAction("Index");
                else
                    ModelState.AddModelError("", "Key is not active to delete");

            return RedirectToAction("Index");
        }
    }
}

FileBasedDBApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FileBasedDBApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FileBasedDBApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

FileBasedDBApplication/Views/JSonDataObject/Create.cshtml
@model FileBasedDBApplication.Models.JsonStorageTable

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>JsonStorageTable</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeToLive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeToLive, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeToLive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FileBasedDBApplication/Views/JSonDataObject/Details.cshtml
@model FileBasedDBApplication.Models.JsonStorageTable

@{
    ViewBag.Title = "READ AND DELETE";
}

<h2>JSON INFORMATION</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Key)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Key)
                @Html.HiddenFor(model => model.Key)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Value)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Value)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CreatedDate)
                @Html.HiddenFor(model => model.CreatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TimeToLive)
            </dt>

            <dd>
                @Html.HiddenFor(model => model.TimeToLive)
                @Html.DisplayFor(model => model.TimeToLive)
            </dd>

        </dl>
        <div class="form-group">
            @if(Model.Active)
            {
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Delete" class="btn btn-default" />
                </div>
            }
        </div>
    </div>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
}

FileBasedDBApplication/Views/JSonDataObject/Index.cshtml
@model IEnumerable<FileBasedDBApplication.Models.JsonStorageTable>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Key)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeToLive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            Action
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Key)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeToLive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @if (item.Active)
                {
                    @Html.ActionLink("Read", "Details", new { id = item.Key })
                }
            </td>
        </tr>
    }

</table>

FileBasedDBApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "JSonDataObject")</li>                  
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>